### PR TITLE
Initial LTE RDL

### PR DESCRIPTION
**Pull request by smooresni**

### CODE REVIEW

**Comment by smooresni** [comment]
@mdwhitten i think the machine used to run the checks doesn't have LTE .NET installed.

**Comment by mdwhitten** [comment]
Hey @smooresni ,

Actually, that is a bit of red herring. If you look at the Code Validation step you'll find the real problem. Trying running the PowerShell script located at _/build-tools/RunConformityChecks.ps1_ and you'll find a number of issues that are requirements based on the [CONTRIBUTING](https://github.com/NISystemsEngineering/rfic-reference-design-libraries-csharp/blob/master/CONTRIBUTING.md) document. The reason the build itself failed is because you have _Specific Version_ set to true for the references in the project, and our exact version numbers don't match.

**Comment by smooresni** [comment]
@mdwhitten believe i fixed everything. will need to add the SG unit tests into #46 and merge into this before submitting for review.

**Comment by mdwhitten** [comment]
Same comment over here as on the LabVIEW code - could we do a rebase operation for this branch? No reason as far as I can tell that this depends on the other code. This would avoid having to merge the SG changes later and keep them functionally separate.

**Comment by smooresni** [comment]
> Same comment over here as on the LabVIEW code - could we do a rebase operation for this branch? No reason as far as I can tell that this depends on the other code. This would avoid having to merge the SG changes later and keep them functionally separate.

You betcha, done!

**Comment by smooresni** [comment]
Some line ending normalization made it into this pull request for other files inadvertently.

**Pull request merged**
