### PR TITLE
Add GetDefault() methods to structs and obsoleted old methods

### PR DESCRIPTION
**Pull request by smooresni**
@mdwhitten this is in response to #29

### CODE REVIEW

**Comment by mdwhitten** [comment]
@smooresni This is really great; thanks for doing this. A few questions:

1. Whenever I make changes like this that pertain to the structure of all modules, I like to make sure I apply it consistently across the codebase. Hence, I'd like to implement this change across all modules. Would you be willing to do so for all the other modules? You'd have to update a few examples along the way.
2. In this case, the [Contributing file](https://github.com/NISystemsEngineering/rfic-reference-design-libraries-csharp/blob/master/CONTRIBUTING.md#data-types) has a description of how default values are supposed to be set for individual structs. Could you update this file to reflect the new design requirements?
3. I think deprecating the old methods is a brilliant move, and one that I should be implementing more regularly. However, in this case I just modified all of the default value methods to standardize them to fix #4. So, these new methods have been in place for only 2 weeks. I think my guidance in this particular case is that no one is even using the 2 week old method yet, so we can probably safely modify these and drop the deprecation. Do you agree or have other thoughts?

**Comment by smooresni** [comment]
> @smooresni This is really great; thanks for doing this. A few questions:
> 
> 1. Whenever I make changes like this that pertain to the structure of all modules, I like to make sure I apply it consistently across the codebase. Hence, I'd like to implement this change across all modules. Would you be willing to do so for all the other modules? You'd have to update a few examples along the way.
> 2. In this case, the [Contributing file](https://github.com/NISystemsEngineering/rfic-reference-design-libraries-csharp/blob/master/CONTRIBUTING.md#data-types) has a description of how default values are supposed to be set for individual structs. Could you update this file to reflect the new design requirements?
> 3. I think deprecating the old methods is a brilliant move, and one that I should be implementing more regularly. However, in this case I just modified all of the default value methods to standardize them to fix #4. So, these new methods have been in place for only 2 weeks. I think my guidance in this particular case is that no one is even using the 2 week old method yet, so we can probably safely modify these and drop the deprecation. Do you agree or have other thoughts?

Yes, yes, and agreed. Will update and push to pull request.

**Comment by smooresni** [comment]
@mdwhitten I've completed all the updates but didn't update the automation code. Seems the sequence is looking for a folder named "Builds" at the root that doesn't exist. I could have put the dependencies in a folder I created myself but opted not to.

**Comment by mdwhitten** [comment]
> @mdwhitten I've completed all the updates but didn't update the automation code. Seems the sequence is looking for a folder named "Builds" at the root that doesn't exist. I could have put the dependencies in a folder I created myself but opted not to.

Thanks for updating all of the examples as well! For future reference, to run the TestStand sequences, you just need to create a **Release** build from the RDL solution. [Based on the contribution guidelines](https://github.com/NISystemsEngineering/rfic-reference-design-libraries-csharp/blob/master/CONTRIBUTING.md#building-and-preparing-for-distribution) all modules place their release builds in the builds folder you recognized. I didn't want debug builds being placed in that directory. I'll update the NR sequence (that's why your build failed) and accept the commit.

**Pull request merged**
