### PR TITLE
Add downlink support to NR

### PR DESCRIPTION
**Pull request by smooresni**

### CODE REVIEW

**Comment by mdwhitten** [comment]
Excellent, thanks for getting this done so soon @smooresni. Any chance you would be able to finish updating the sequence while you’re here? I haven’t gotten very far yet. I’m sure @heyitsdale would be very appreciative :).

**Comment by smooresni** [comment]
@mdwhitten I updated the automation sequence but would love it if you could look it over first

**Comment by smooresni** [comment]
I haven't tried running it yet.

**Comment by mdwhitten** [comment]
> @mdwhitten I updated the automation sequence but would love it if you could look it over first

@smooresni We can follow up on this a bit later, but there were two main changes to make, and then the rest looked good.
- We load waveform information via a property loader file next to each waveform. This file needed to be updated to reflect the changes to the signal config struct that had been made.
- For results, rather than dumping them to the local of the relevant sequence (i.e. ACP sequence locals) there is a defined location for them under FileGlobabls.Current_Sweep_Step.Results.<Struct>

With this in place I am now merging.

**Pull request merged**
