### PR TITLE
CHANGE: Execute SetScript function after dpd waveform is written to rfsg and before initiate call

### PR DESCRIPTION
**Pull request by bbachmanNI**
DPD PerformMemoryPolynomial -> Added the call to SG.Configure ContinuousGeneration before the final intiate to execute the RFSG SetScript again which is necessary to write all parameters down to the driver.

### CODE REVIEW

**Comment by mdwhitten** [comment]
Sorry, I’m a little late to this conversation. My concern with this approach is that we don’t know what type of generation the user is intending to use and hence why we don’t reconfigure the script by default. I am not sure how likely this is, but wondered what if someone was doing bursted generation for WLAN? We should not reset their script generation. 

Rather than using RFSG set script to generate, could we just manually write to the driver only the things that could change? i.e. skip playback library and just write the waveform and PAPR to the generator before re-initiating. FYI @manderseck

**Comment by mkrmasch** [comment]
> 
> 
> Sorry, I’m a little late to this conversation. My concern with this approach is that we don’t know what type of generation the user is intending to use and hence why we don’t reconfigure the script by default. I am not sure how likely this is, but wondered what if someone was doing bursted generation for WLAN? We should not reset their script generation.
> 
> Rather than using RFSG set script to generate, could we just manually write to the driver only the things that could change? i.e. skip playback library and just write the waveform and PAPR to the generator before re-initiating. FYI @manderseck

--> Or we store the script that has been generated....

**Comment by mdwhitten** [comment]
My understanding is that this is superseded by some of @smooresni's other work in #86, right? If so please close this after confirming.

**Comment by smooresni** [comment]
> My understanding is that this is superseded by some of @smooresni's other work in #86, right? If so please close this after confirming.

yes this is superseded by #87 . closing without merge.

**Pull request closed without merging**
